refresh_oxford/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from .views import EventDetail, EventList, Home, SignUp


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', Home.as_view()),
    url(r'^events/$', EventList.as_view(), name='event-list'),
    url(r'^events/(?P<pk>\d+)/$', EventDetail.as_view(), name='event-detail'),
    url(r'^terms/$', TemplateView.as_view(template_name='terms.html'), name='terms'),
    url(r'^signup/$', SignUp.as_view(), name='signup'),
    url(r'favicon.ico', RedirectView.as_view(url=settings.STATIC_URL + 'static/favicon.ico')),
    url(r'^admin/', include(admin.site.urls)),

    url('', include('feincms.urls')),
)

urlpatterns += staticfiles_urlpatterns()

refresh_oxford/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _
from feincms.content.richtext.models import RichTextContent
from feincms.module.page.models import Page


class Attendee(models.Model):
    event = models.ForeignKey('Event', blank=True)
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    github_username = models.CharField(max_length=255, null=True, blank=True)
    extra = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['pk']
        unique_together = ('email', 'event')

    def __unicode__(self):
        return self.name


class EventManager(models.Manager):
    def current(self):
        try:
            return self.get_query_set().filter(current=True)[0]
        except IndexError:
            return self.get_query_set().none()


class Event(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    where = models.TextField()
    start = models.DateTimeField()
    finish = models.DateTimeField()
    current = models.BooleanField(default=False)

    objects = EventManager()

    class Meta:
        ordering = ['start']

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('event-detail', pk=self.pk)

class MailingListPerson(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255, unique=True)

    def __unicode__(self):
        return self.name


Page.register_templates(
    {
        'key': '1col',
        'title': _('One column'),
        'path': 'base.html',
        'regions': (
            ('main', _('Main content')),
        ),
    },
)
Page.create_content_type(RichTextContent)

refresh_oxford/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, Submit
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Attendee, MailingListPerson


class MailingListForm(forms.ModelForm):
    class Meta:
        model = MailingListPerson

    helper = FormHelper()
    helper.form_method = 'post'
    helper.layout = Layout(
        Fieldset('',
            Field('email', placeholder='Email address'),
            Field('name', placeholder='Name'),
            Submit('submit', _('Sign Up!'), css_class='submit'),
        )
    )


class SignUpForm(forms.ModelForm):
    class Meta:
        fields = ('name', 'email', 'github_username', 'extra')
        model = Attendee

    helper = FormHelper()
    helper.form_method = 'post'
    helper.layout = Layout(
        Fieldset('',
            Field('name', placeholder='Name*'),
            Field('email', placeholder='Email address*'),
            Field('github_username', placeholder='GitHub User (Optional)'),
            Field('extra', rows='5', placeholder='Anything else? Dietary requirements etc.'),
            Submit('submit', _('Sign Up!'), css_class='submit'),
        )
    )

refresh_oxford/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, DetailView, ListView

from .forms import MailingListForm, SignUpForm
from .models import Attendee, Event, MailingListPerson


class EventDetail(DetailView):
    model = Event
    template_name = 'event_detail.html'


class EventList(ListView):
    model = Event
    template_name = 'event_list.html'


class Home(CreateView):
    form_class = MailingListForm
    model = MailingListPerson
    success_url = '/'
    template_name = 'home.html'

    def form_valid(self, form):
        msg = "Thanks for signing up for emails, we'll send you deails about any future emails"
        messages.info(self.request, msg)
        return super(Home, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['event'] = Event.objects.current()
        return context


class SignUp(CreateView):
    form_class = SignUpForm
    model = Attendee
    success_url = '/'
    template_name = 'signup.html'

    def dispatch(self, request, *args, **kwargs):
        self.event = Event.objects.current()
        if not self.event:
            return HttpResponseRedirect('/')
        return super(SignUp, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        msg = "Thanks for signing up, we'll email you more details closer to the date."
        messages.info(self.request, msg)
        form.instance.event = self.event
        return super(SignUp, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(SignUp, self).get_context_data(**kwargs)
        context['event'] = self.event
        return context

refresh_oxford/templates/base.html
<!doctype html>
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
{% load feincms_tags %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>{% block title %}{% endblock title %}</title>

    <meta name="viewport" content="width=device-width">

    {% block base_style %}
    <link rel="stylesheet" href="{{ STATIC_URL }}styles/main.css">
    {% endblock base_style %}

    {% block extra_style %}{% endblock extra_style %}

    {% block modernizr %}
    <script src="{{ STATIC_URL }}scripts/libs/modernizr-2.5.3.min.js"></script>
    {% endblock %}

    {% block jquery_js %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ STATIC_URL }}scripts/libs/jquery-1.7.2.min.js"><\/script>')</script>
    {% endblock jquery_js %}

    {# Include your plugins before main.js and your other JS after main.js #}

    <script src="{{ STATIC_URL }}scripts/plugins/fontdetect.js"></script>
    <script src="{{ STATIC_URL }}scripts/plugins/jquery.placeholder.min.js"></script>
    <script src="{{ STATIC_URL }}scripts/main.js"></script>

    {% block extra_script %}{% endblock extra_script %}

    {% block extra_head %}{% endblock extra_head %}
</head>

{% block body %}
<body id="page-{% block bodyid %}{% endblock bodyid %}" class="{% block bodyclass %}{% endblock bodyclass %}">
{% block pre_wrap %}{% endblock pre_wrap %}
    {% block wrap %}
    <div id="wrap">
        {% block wrap_content %}
            {% block preheader %}{% endblock preheader %}

            {% block header %}
            <a href="/">
                <header id="site-header">
                <div class="structure">
                    {% block header_content %}
                    <nav id="site-nav">
                    </nav>
                    {% endblock header_content %}
                </div>
                </header>
            </a>
            {% endblock header %}

            {% block page %}
            <div id="site-main">
                {% if messages %}
                {% block messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endblock messages %}
                {% endif %}
                <div class="structure">
                    <h2>{% block page_title %}{{ feincms_page.title }}{% endblock page_title %}</h2>
                    {% block page_content %}
                    {% block content %}
                        {% feincms_render_region feincms_page 'main' request %}
                    {% endblock content %}
                    {% endblock page_content %}
                </div>
            </div>
            {% endblock page %}
        {% endblock wrap_content %}
    </div>

    {% block footer %}
    <footer id="site-footer">
    <div class="structure">
        {% block footer_content %}
        <p>&copy; Copyright 2012 Incuna Ltd. All rights reserved</p>
        <p><a href="{% url 'terms' %}">Terms &amp; Conditions</a> <a href="/code-of-conduct/">Code of Conduct</a></p>
        {% endblock footer_content %}
    </div>
    </footer>
    {% endblock footer %}
    {% endblock wrap %}
    {% block post_wrap %}{% endblock post_wrap %}

    {% block google_analytics %}
    <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.-->
    <script>
        var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
        (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
    </script>
    {% endblock google_analytics %}
</body>
{% endblock body %}
</html>

refresh_oxford/templates/code-of-conduct.html
{% extends "base.html" %}

{% block page_title %}
  <h2>Code of Conduct</h2>
{% endblock page_title %}

{% block content %}
  <p>Harassment includes offensive verbal comments related to gender, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.</p>

  <p>Participants asked to stop any harassing behavior are expected to comply immediately.</p>

  <p>Be careful in the words that you choose. Remember that sexist, racist, and other exclusionary jokes can be offensive to those around you. Excessive swearing and offensive jokes are not appropriate for Refresh Oxford.</p>

  <p>If a participant engages in behavior that violates this code of conduct, the hack day organizers may take any action they deem appropriate, including warning the offender or expulsion from the hack day.</p>
  
  <h3>License</h3>
  <p>Conference Code of Conduct by <a href="https://us.pycon.org/2013/about/code-of-conduct/">https://us.pycon.org/2013/about/code-of-conduct/</a> is licensed under a Creative Commons Attribution 3.0 Unported License.</p>
{% endblock %}

refresh_oxford/templates/event_detail.html
{% extends "base.html" %}

{% block content %}
{{ event }}
{% endblock %}

refresh_oxford/templates/event_list.html
{% extends "base.html" %}

{% block content %}
{% for event in event_list %}
    <a href="{{ event.get_absolute_url }}">{{ event }}</a>
{% endfor %}
{% endblock %}

refresh_oxford/templates/home.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load gravatar %}

{% block page_title %}What is Refresh Oxford?{% endblock %}

{% block content %}
<p>Refresh Oxford is Oxford's premier hackday event where the best developers, designers, front-enders and UX-ers come together to create amazing projects in just one day. Hosted by digital agency <a href="http://incuna.com/">Incuna</a> we'll provide the space, good food and drinks…</p>

{% if event %}
    <h3 class="invited">You're invited!</h3>
    <p class="address">{{ event.start|date:"l, F j, Y" }} from: {{ event.start|date:"H:i" }} — {{ event.finish|date:"H:i" }}<br>
    {% if event.map %}<a href="{{ event.map }}">{{ event.where }}</a>{% endif %}  It’s free!</p>
    <p class="register"><a href="{% url 'signup' %}">Register Now!</a></p>

    {% if event.attendee_set %}
    <h2>So Who's Coming?</h2>
    {% for attendee in event.attendee_set.all %}
        <img src="{% gravatar_for_email attendee.email %}" title="{{ attendee.name }}">
    {% endfor %}
    {% endif %}
{% endif %}

{% if event %}
<h2>Can't make this one?</h2>
{% else %}
<h2>Nothing coming up =(</h2>
{% endif %}
<p>That's too bad! Sign up to our mailing list to find out when the next Refresh Oxford is going to happen.</p>

{% crispy form %}

{% endblock %}

refresh_oxford/templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block page_title %}
<h2>Refresh Oxford
    <span>{{ event.start|date:"jS F" }}</span>
    <span>{{ event.start|date:"H:i" }} - {{ event.finish|date:"H:i" }}</span>
</h2>
{% endblock page_title %}

{% block content %}
    {% crispy form %}
    <p class="signup-greeting">See you on {{ event.start|date:"F jS" }}!</p>
{% endblock %}